import React from "react";
import Rooms from "./Rooms";
import styles from "./rooms.module.css";
import {nanoid} from "nanoid"

let roomData = [
  {
    id: 1,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },

  {
    id: 2,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },
  {
    id: 3,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },

  {
    id: 4,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },
  {
    id: 5,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },
  {
    id: 6,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },
  {
    id: 7,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },
  {
    id: 8,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },
  {
    id: 9,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },
  {
    id: 10,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },
  {
    id: 11,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  },
  {
    id: 1,
    a: "220 sq ft",
    b: "Sleeps 3",
    c: "1 King Bed OR Twin Beds",
    d: "Free high-speed internet",
    e: "Free self Parking",
    f: "Breakfast buffet",
    g: "+$0",
    h: "Breakfast buffet + Airport shuttle",
    i: "+$40",
    j: "Half-board + Special deal More Details",
    k: "+$50",
    l: "Full board + Special deal More Details",
    m: "+$32",
    n: "Resort credit + Special deal More Details",
    o: "+$97",
  }
];
console.log(roomData.length)
const Roomdetails = () => {
  return (
    <>
      <div className={styles.conatiner}>
        {roomData.map((el) => {
          return <Rooms key={nanoid()} {...el} />;
        })}
      </div>
    </>
  );
};

export default Roomdetails;
